apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=b743b73e93d1428952139ec2f2f5ae0298b72a33
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=b743b73e93d1428952139ec2f2f5ae0298b72a33

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/redhat-user-workloads/konflux-mintmaker-tenant/mintmaker-refactoring-pipelinerun
    newTag: b743b73e93d1428952139ec2f2f5ae0298b72a33

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../components/rh-certs
